version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    command: ["nginx", "-g", "daemon off;"]